# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf6f39419db7b6de50802bdd7b4152e37199fbc47502e00fb83c018df9991d6e600df7a93961a87782761d4414a7281da2eb45f46341283f9dcfc54616d37238

test:
  secret_key_base: 2597a966578d738bc25b91236f9dcd3f2a32087aae9cb280106dd9783cb74d481cc5c75127dd0f265cafd4504e1184e6a7bdeb0748a0f39c16a21905f5c54bf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
